name: form
description: Form state management.
version: 1.0.0+1

environment:
  sdk: '>=2.18.7 <3.0.0'

dependencies:
  freezed_annotation: ^2.2.0

dev_dependencies:
  build_runner: ^2.3.3
  freezed: ^2.3.2
  test: ^1.23.1
