name: {{#snakeCase}}{{name}}{{/snakeCase}}

packages:
  - packages/**

ignore:
  - '**/example/*'
  - synthetic_package

scripts:
  generate:
    run: melos exec -c 1 --depends-on="build_runner" --flutter -- "flutter pub run build_runner build --delete-conflicting-outputs"
    description: Build all generated files.
    select-package:
      build_runner: true

  format:
    run: flutter format --set-exit-if-changed lib test
    description: Format in all packages.
    select-package:
      flutter: true

  format:fix:
    run: flutter format --fix .
    description: Run `flutter format --fix` in all packages.
    select-package:
      flutter: true

  analyze:
    run: flutter analyze .
    description: Analyze all packages.
    select-package:
      flutter: true
  
  test:
    run: melos exec -c 4 --fail-fast -- "flutter test --no-pub --coverage --test-randomize-ordering-seed random"
    description: Run Flutter tests for a specific package in this project.
    select-package:
      flutter: true
      dir-exists: test

environment:
  sdk: '>=2.17.0 <3.0.0'
  flutter: '>=3.0.0 <4.0.0'