name: {{#snakeCase}}{{name}}{{/snakeCase}}
description: {{description}}
version: 0.0.1+1
publish_to: none

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^1.0.3
  intl: ^0.17.0

dev_dependencies:
  dart_code_metrics: ^4.6.0
  flutter_test:
    sdk: flutter
  mocktail: ^0.2.0

flutter:
  uses-material-design: true
  generate: true
