services:
  api:
    build: 
      context: ./api
      target: dev
    volumes:
      - ./api:/app
    depends_on:
      - database
    restart: unless-stopped
    environment:
      APP_SECRET: ${APP_SECRET}
      PUBLIC_ENTRYPOINT: https://${SERVER_NAME:-localhost}
      DATABASE_URL: postgresql://${POSTGRES_USER:-admin}:${POSTGRES_PASSWORD:-root}@database:5432/${POSTGRES_DB:-app}

  database:
    image: postgres:${POSTGRES_VERSION:-15}-alpine
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-app}
      # You should definitely change the password in production
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-root}
      - POSTGRES_USER=${POSTGRES_USER:-admin}
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./docker/postgres/schema.sql:/docker-entrypoint-initdb.d/schema.sql
      # you may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./etc/postgres/data:/var/lib/postgresql/data

volumes:
  db_data: