name: app_name
description: Flutter Application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: 3.10.6

dependencies:
  android_intent_plus: ^4.0.2
  cached_network_image: ^3.2.3
  dio: ^5.3.2
  flex_color_scheme: ^7.2.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_hooks: ^0.20.0
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^2.4.1
  gap: ^3.0.1
  go_router: ^10.0.0
  hooks_riverpod: ^2.1.3
  intl: ^0.18.0
  json_annotation: ^4.7.0
  jwt_decoder: ^2.0.1
  rxdart: ^0.27.7
  shared_preferences: ^2.0.15
  uni_links: ^0.5.1
  url_launcher: ^6.1.7

dev_dependencies:
  build_runner:
  flutter_test:
    sdk: flutter
  freezed: ^2.4.1
  json_serializable: ^6.5.4
  mocktail: ^1.0.0

flutter:
  uses-material-design: true
  generate: true
