name: app_name
description: Flutter Application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: 3.3.8

dependencies:
  android_intent_plus: ^3.1.5
  cached_network_image: ^3.2.3
  dio: ^4.0.6
  flex_color_scheme: ^6.1.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_hooks: ^0.18.5+1
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^2.2.0
  gap: ^2.0.1
  go_router: ^6.0.0
  hooks_riverpod: ^2.1.3
  intl: ^0.17.0
  json_annotation: ^4.7.0
  jwt_decoder: ^2.0.1
  rxdart: ^0.27.7
  shared_preferences: ^2.0.15
  uni_links: ^0.5.1
  url_launcher: ^6.1.7

dev_dependencies:
  build_runner:
  flutter_test:
    sdk: flutter
  freezed: ^2.2.0
  json_serializable: ^6.5.4
  mocktail: ^0.3.0

flutter:
  uses-material-design: true
  generate: true
